EShop/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'EShop'
urlpatterns = [

    # root pages
    path('', HomeView.as_view(), name='home'),
    path('About/', AboutView.as_view(), name='about'),
    path('Contact/', ContactView.as_view(), name='contact'),
    path('All-products/', AllProductsView.as_view(), name='allproducts'),
    path('Product/<slug:slug>/', ProductDetailView.as_view(), name='productdetail'),

    # cart urls
    path('Add-to-cart-<int:pro_id>/', AddToCartView.as_view(), name='addtocart'),
    path('My-cart/', MyCartView.as_view(), name='mycart'),
    path('Manage-cart/<int:cp_id>/', ManageCartView.as_view(), name='managecart'),
    path('Empty-cart/', EmptyCartView.as_view(), name='emptycart'),

    # checkout url
    path('Checkout/', CheckOutView.as_view(), name='checkout'),

    # authentication urls
    path('Register/', CustomerRegistrationView.as_view(),
         name='customerregistration'),
    path('login/', CustomerLoginView.as_view(), name='customerlogin'),
    path('logout/', CustomerLogoutView.as_view(), name='customerlogout'),
    path('reset-password/', ResetPasswordView.as_view(), name='resetpassword'),

    # my profile url
    path('Profile/', CustomerProfileView.as_view(), name='customerprofile'),
    path('profile/order-<int:pk>/', CustomerOrderDetailView.as_view(),
         name='customerorderdetail'),

    # serching url
    path('search/', SearchView.as_view(), name='search'),

    # admin urls
    path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
    path('admin-home/', AdminHomeView.as_view(), name='adminhome'),
    path('admin-orderdetail/<int:pk>/',
         AdminOrderDetailView.as_view(), name='adminorderdetail'),
    path('admin-orders-list/', AdminOrderListView.as_view(), name='adminorderlist'),
    path('admin-order-<int:pk>-change/',
         AdminorderStatusChangeView.as_view(), name='adminorderstatuschange'),
    path('admin-product-list/', AdminProductListView.as_view(),
         name='adminproductlist'),
    path('admin-product-detail/<int:pk>/',
         AdminProductDetailView.as_view(), name='adminproductdetail'),
    path('admin-product-create/', AdminProductCreateView.as_view(),
         name='adminproductcreate'),

    path('admin-product-create-many/',
         AdminProductCreateView.as_view(), name='adminproductcreatemany')

]

ecommerce_Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('EShop.urls'))
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EShop/models.py
from django.db import models
from django.contrib.auth.models import User

# creating admin for e-commerce website


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=20)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='admins')

    def __str__(self):
        return self.user.username


# creating customers for our e-commerce website
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


# adding category for products
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


# adding products
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


# adding multiple images for a product
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/')

    def __str__(self):
        return self.product.title


# creating cart to the customer
class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


# customer add product into the cart
class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct: " + str(self.id)


# customer order products
view_status = (
    ("Order_Received", "Order_Received"),
    ("Order_Processing", "Order_Processing"),
    ("On_The_Way", "On_The_Way"),
    ("Order_Completed", "Order_Completed"),
    ("Order_Canceled", "Order_Canceled"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=20)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=100, choices=view_status)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/adminpages/adminbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}  {% endblock %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <a href="{% url 'EShop:adminhome' %}">Admin Home</a> |
        <a href="{% url 'EShop:adminorderlist' %}">All Orders List</a> |
        <a href="{% url 'EShop:adminproductlist' %}">All Products List</a> |
        <a href="{% url 'EShop:adminproductcreate' %}">Admin Add Product</a> |
        <a href="{% url 'EShop:home' %}" target="_blank">Visit ecomsite</a> |
    </div>
    {% block body %}    


    {% endblock %}
</body>
</html>

templates/adminpages/adminhome.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Admin home{% endblock %}

{% block body %}
<div class="container">
    <div class="col-md-12">
        <h3 class="my-3">Pending Orders</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>SN</th>
                    <th> Order ID</th>
                    <th>Customer</th>
                    <th>Ordered On</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for order in pendingorders %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a href="{% url 'EShop:adminorderdetail' order.pk %}">#ORDER_{{order.id}}</a></td>

                    <td> {{order.ordered_by}} </td>
                    <td> {{order.created_at}} </td>
                    <td> {{order.total}} </td>

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/adminpages/adminlogin.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Admin login{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Admin Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <!-- <input type="submit" value="login"> -->
                <button class="btn btn-success">Login As a Admini</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %} 

templates/adminpages/adminorderdetail.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}

{% block title %}Admin Order Detail{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3>order details</h3>
            <hr>
            <p><span>Order ID: </span>#Order_{{obj_obj.id}}</p>
            <p><span>Order Status: </span>{{obj_obj.order_status}}</p>
            <p><span>Order On: </span>{{obj_obj.created_at}}({{obj_obj.created_at|timesince}} ago)</p>
            <hr>
            <p><span>Customer Information: </span> By {{ obj_obj.ordered_by }}, {{ obj_obj.mobile}}, {{ obj_obj.email}}
            </p>
            <hr>
            <p><span>Shipping Address: </span>{{ obj_obj.shipping_address }}</p>

            <h4>ordered Items</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in obj_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td> {{forloop.counter}} </td>
                        <td><a target="_blank" href="{% url 'EShop:productdetail' cp.product.slug %}">
                                {{cp.product.title}}({{cp.product.id}}) </a></td>
                        <td> {{cp.rate}} </td>
                        <td> {{cp.quantity}} </td>
                        <td> {{cp.subtotal}} </td>
                    </tr>
                    <tr>
                        <td colspan="4" class="text-right">Total: </td>
                        <td>Rs {{obj_obj.total|intcomma}} /.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <form action="{% url 'EShop:adminorderstatuschange' obj_obj.pk %}" method="POST">
                {% csrf_token %}
                <select name="status">
                    {% for i, j in allstatus %}
                    <option value="{{i}}" {% if i == obj_obj.order_status %} selected {% endif %}>{{j}} </option>
                    {% endfor %}
                </select><br>
                <button class="btn btn-info">status changed</button>
            </form>
        </div>
    </div>
</div>


{% endblock %}

templates/adminpages/adminorderlist.html
{% extends 'adminpages/adminbase.html' %}

{% block title %}Admin order list{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="my-3">
                All Orders <span class="text-info"> (With Status of Order)</span>
            </h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th> Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in allorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'EShop:adminorderdetail' order.pk %}">#ORDER_{{order.id}}</a></td>
                        <td> {{order.ordered_by}} </td>
                        <td> {{order.created_at}} </td>
                        <td> {{order.total}} </td>
                        <td> {{order.order_status}} </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/adminpages/adminproductcreate.html
{% extends 'adminpages/adminbase.html' %}

{% block title %} Admin Product Add {% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-10 mx-auto">
            <hr><h3>Admin Create Product</h3>
            <hr>
            <form action="{% url 'EShop:adminproductcreate' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success">Add Product</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/adminproductdetails.html
{% extends 'adminpages/adminbase.html' %}

{% block title %} {{product.title}}{% endblock %}

{% block body %}
    <div class="container">
        <h3 class="my-3">{{productdetail.title}} </h3><hr>
        <div class="row">
            <div class="col-md-4">
                <img src="{{productdetail.image.url }}"  class="img-fluid" alt="">
                <div class="row">
                    {% for pi in productdetail.productimage_set.all %}
                    <div class="col-md-4"><a href="{{ pi.image.url }}" target="_blank" >
                        <img class="image-fluid" style="height: 100px;" src="{{ pi.image.url }}" alt=""></a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-8">
                <h4>TITLE: {{ productdetail.title}} (viewed<sup>{{productdetail.view_count}}</sup>)</h4>
                <h4>CATEGORY:  {{ productdetail.Category}} </h4>
                <h5>Price RS. <strike> {{ productdetail.marked_price}}</strike> {{ productdetail.selling_price}} </h5>
                <a href="{% url 'EShop:addtocart' productdetail.id  %}" class="btn btn-info" >ADD TO CART</a><hr>

                <p>WARRANTY: {{productdetail.warranty}} </p>
                <p>RETURN POLICY: {{productdetail.return_policy}} </p>
                <hr>
                <p>
                    {{productdetail.description}}
                </p>
            </div>
        </div>
        
    </div>


{% endblock %}

templates/adminpages/adminproductlist.html
{% extends 'adminpages/adminbase.html' %}

{% block title %} All Products {% endblock %}

{% block body %}
<div class="container">
    <hr>

    <h3 class="my-3">Admin All Product List</h3>
    <div class="row">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Product Image</th>
                    <th>Product Title</th>
                    <th>Product Price</th>
                    <th>Product Views</th>
                </tr>
            </thead>
            <tbody>
                {% for ap in allproducts %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><img height="60px" src="{{ap.image.url}}" alt=""></td>
                    <td> <a href="{% url 'EShop:adminproductdetail' ap.id %}"> {{ap.title}}</a></td>
                    <td>{{ap.selling_price}}</td>
                    <td>{{ap.view_count}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}