EShop/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'EShop'
urlpatterns = [

    # root pages
    path('', HomeView.as_view(), name='home'),
    path('About/', AboutView.as_view(), name='about'),
    path('Contact/', ContactView.as_view(), name='contact'),
    path('All-products/', AllProductsView.as_view(), name='allproducts'),
    path('Product/<slug:slug>/', ProductDetailView.as_view(), name='productdetail'),

    # cart urls
    path('Add-to-cart-<int:pro_id>/', AddToCartView.as_view(), name='addtocart'),
    path('My-cart/', MyCartView.as_view(), name='mycart'),
    path('Manage-cart/<int:cp_id>/', ManageCartView.as_view(), name='managecart'),
    path('Empty-cart/', EmptyCartView.as_view(), name='emptycart'),

    # checkout url
    path('Checkout/', CheckOutView.as_view(), name='checkout'),

    # authentication urls
    path('Register/', CustomerRegistrationView.as_view(),
         name='customerregistration'),
    path('login/', CustomerLoginView.as_view(), name='customerlogin'),
    path('logout/', CustomerLogoutView.as_view(), name='customerlogout'),
    path('reset-password/', ResetPasswordView.as_view(), name='resetpassword'),

    # my profile url
    path('Profile/', CustomerProfileView.as_view(), name='customerprofile'),
    path('profile/order-<int:pk>/', CustomerOrderDetailView.as_view(),
         name='customerorderdetail'),

    # serching url
    path('search/', SearchView.as_view(), name='search'),

    # admin urls
    path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
    path('admin-home/', AdminHomeView.as_view(), name='adminhome'),
    path('admin-orderdetail/<int:pk>/',
         AdminOrderDetailView.as_view(), name='adminorderdetail'),
    path('admin-orders-list/', AdminOrderListView.as_view(), name='adminorderlist'),
    path('admin-order-<int:pk>-change/',
         AdminorderStatusChangeView.as_view(), name='adminorderstatuschange'),
    path('admin-product-list/', AdminProductListView.as_view(),
         name='adminproductlist'),
    path('admin-product-detail/<int:pk>/',
         AdminProductDetailView.as_view(), name='adminproductdetail'),
    path('admin-product-create/', AdminProductCreateView.as_view(),
         name='adminproductcreate'),

    path('admin-product-create-many/',
         AdminProductCreateView.as_view(), name='adminproductcreatemany')

]

ecommerce_Website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('EShop.urls'))
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EShop/models.py
from django.db import models
from django.contrib.auth.models import User

# creating admin for e-commerce website


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.CharField(max_length=20)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='admins')

    def __str__(self):
        return self.user.username


# creating customers for our e-commerce website
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


# adding category for products
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


# adding products
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


# adding multiple images for a product
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/images/')

    def __str__(self):
        return self.product.title


# creating cart to the customer
class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


# customer add product into the cart
class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct: " + str(self.id)


# customer order products
view_status = (
    ("Order_Received", "Order_Received"),
    ("Order_Processing", "Order_Processing"),
    ("On_The_Way", "On_The_Way"),
    ("Order_Completed", "Order_Completed"),
    ("Order_Canceled", "Order_Canceled"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=20)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=100, choices=view_status)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/About.html
{% extends 'base.html' %}
{% block title  %}ABOUT-US{% endblock %}
{% block body %}

<div class="addtocart-center">
    <pre class="text-center primary font-weight-bold">
        <h2>Coming Soon..</h2>
        </pre>

</div>

{% endblock %}

templates/addtocart.html
{% extends 'base.html' %}

{% block title %} Add To Cart {% endblock %}

{% block body %}
    <div class="addtocart-center">
        <pre class="text-center">
            <h2>Added in your cart !!</h2><h4><a class="primary" href="{% url 'EShop:home' %}">Explore more Products</a></h4><h4> <a class="text-success" href="{% url 'EShop:mycart' %}">GO to cart & checkout</a></h4>
        </pre>
        
    </div>

{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}

{% block title %}
ALL Products
{% endblock %}

{% block body %}


<!-- <h2 class="deal-title-text">DEALS OF THE DAY</h2>
<div class="box">
    {% for p in page_obj %}
    <div class="card" style="width: 18rem; height: 25rem;">
        <a target="blank" href="{% url 'EShop:productdetail' p.slug %}">
            <img class="img-fluid card-img-top" src="{{ p.image.url }}" style="height: 10rem; object-fit: contain;"
                alt="product image">
            <div class="card-body" style="height: 15rem;">
                <h5 class="card-title text-dark" style="height: 10rem;">{{ p.title}}</h5>
            </div>
        </a>
    </div>
    {% endfor %}

</div> -->





<!-- <div class="container"> -->
    {% for category in allcategories %}
    <h2 class="deal-title-text mt30 text-uppercase">{{category.title}}</h2><hr>
    <div class="row">
        {% for p in category.product_set.all %}

        <div class="card p0 mx-auto my-5" style="width: 18rem; height: 25rem;">
            <a target="blank" href="{% url 'EShop:productdetail' p.slug %}">
                <img class="img-fluid card-img-top" src="{{ p.image.url }}" style="height: 8rem; object-fit: contain;"
                    alt="product image">
                <div class="card-body p0 mt-4" style="height:5rem;">
                    <h5 class="card-title text-dark p0 mx-2 " style="height: 7rem;">{{ p.title|truncatewords:8}}</h5>
                </div>
                    <p class="card-body p0 text-normal mx-2" style="height: 8rem;">
                        {{p.description|truncatewords:20}}
                    </p>
                    <a href="{% url 'EShop:addtocart' p.id  %}" style="height: 5rem;" class="btn addtocart-btn">Add To Cart</a>
            </a>
        </div>



            <!-- <div class="col-md-4">
                <div class="m-4">
                <h3><a href="{% url 'EShop:productdetail' p.slug %}">{{p.title|truncatewords:5}}</h3>
                <img src="{{ p.image.url }}" style="height: 200px; width: 150px;" alt="">
                <p>Price: <strike>Rs. {{p.marked_price}} </strike> Rs. {{p.selling_price}} </p></a>
                <a href="{% url 'EShop:addtocart' p.id  %}" class="btn btn-primary">Add To Cart</a>
                </div>
            </div> -->
            {% endfor %}


    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{%  static 'EShop/style.css' %}">
    
      </head>
<body>

 <!-- <li>
                <form class="searchform form-inline my-2 my-lg-0" action="{% url 'EShop:search' %}" method="GET">
                  <input class="form-control mr-sm-2" name="keyword" required type="search" placeholder="Search" aria-label="Search">
                  <button class="submitform btn" type="submit">Search</button>
                </form> 
              </li> -->


      <nav class="navbar">
        
        <div class="brand-title font-weight-bold"><a href="{% url 'EShop:home' %}">Our E-commerce</a></div>
        <a href="#" class="toggle-button">
          <span class="bar"></span><span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
        </a>
        <div>
          <form class=" searchform form-inline my-lg-0" action="{% url 'EShop:search' %}" method="GET">
            <input class="form-control mr-sm-2" name="keyword" required type="search" placeholder="Search " aria-label="Search">
            <button class="btn-color search-btn btn text-white m--15 my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
        <div class="navbar-links">
          <ul>
           
            <li><a class="font-weight-bold" href="{% url 'EShop:home' %}">Home</a></li>
            <li>
              <a class="font-weight-bold" href="{% url 'EShop:allproducts' %}">Categories</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                My Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}            
                <a class="dropdown-item font-weight-bold" href="{% url 'EShop:customerprofile' %}">My Profile </a>
                <a class="dropdown-item font-weight-bold" href="{% url 'EShop:contact' %}">Contact</a>
                <a class="dropdown-item font-weight-bold" href="{% url  'EShop:about' %}">About</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item font-weight-bold" href="{% url 'EShop:customerlogout' %}"> Logout</a>
                {% else %}
                <a class="dropdown-item font-weight-bold" href="{% url 'EShop:contact' %}">Contact</a>
                <a class="dropdown-item font-weight-bold" href="{% url  'EShop:about' %}">About</a>
            
                <a class="dropdown-item font-weight-bold" href="{% url 'EShop:customerlogin' %}">Login</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item font-weight-bold" href="{% url 'EShop:customerregistration' %}">Register</a>
                {% endif %}
              </div>
            </li>
            <li>
              <a class="font-weight-bold" href="{% url 'EShop:mycart' %}">Cart</a>
            </li>
          </ul>
        </div>
      </nav>






<!-- 

    <nav class="navbar navbar-expand-lg">
        <a class="navbar-brand font-weight-bold" href="{% url 'EShop:home' %}">Our Ecommerce </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'EShop:home' %}">Home<span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'EShop:allproducts' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link font-weight-bold" href="{% url 'EShop:mycart' %}">Cart</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        My Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.customer %}

                        <a class="dropdown-item font-weight-bold" href="{% url 'EShop:customerprofile' %}">My Profile </a>
                        <a class="dropdown-item font-weight-bold" href="{% url 'EShop:contact' %}">Contact</a>
                        <a class="dropdown-item font-weight-bold" href="{% url  'EShop:about' %}">About</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item font-weight-bold" href="{% url 'EShop:customerlogout' %}"> Logout</a>
                        {% else %}
                        <a class="dropdown-item font-weight-bold" href="{% url 'EShop:contact' %}">Contact</a>
                        <a class="dropdown-item font-weight-bold" href="{% url  'EShop:about' %}">About</a>

                        <a class="dropdown-item font-weight-bold" href="{% url 'EShop:customerlogin' %}">Login</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item font-weight-bold"
                            href="{% url 'EShop:customerregistration' %}">Register</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'EShop:search' %}" method="GET">
                <input class="form-control mr-sm-2" name="keyword" required type="search" placeholder="Search"
                    aria-label="Search">
                <button class="btn btn-dark text-white btn-outline-info my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav> -->
    {% block body %}
      
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
        <script>
          const toggleButton = document.getElementsByClassName('toggle-button')[0]
          const navbarLinks = document.getElementsByClassName('navbar-links')[0]

          toggleButton.addEventListener('click', () => {
            navbarLinks.classList.toggle('active')
          })
        </script>
</body>

</html>

templates/checkout.html
{% extends 'base.html' %}

{% block title %} Checkout {% endblock %}

{% block body %}
<h2 class="my-3" style="text-align: center;"><span>Checkout Form</span></h2><br>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <ul class="billing p0">
                <li class="billing-detail"><h4>Billing details</h4></li>
                <li class="cart-update"><a href="{% url 'EShop:mycart' %}">Change Order</a></li>
            </ul>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
            <button type="submit" class="btn btn-lg btn-block">Place Your Order</button>
            </form>
        </div>
        <div class="your-order px-0 col-md-4">
            <h3 class="ml-2">Your Order</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Products</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
        
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}})</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="3" class="text-left">Total</th>
                        <th>Rs {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
            <div class="mb20">
                <h4 class="ml-2">Payment<hr></h4>
                <input class="ml-2" type="radio" checked id="html" name="fav_language" value="HTML">
                  <label for="html">CASH ON DELIVERY</label><br>
            </div>        
        </div>
    </div>
</div>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% block title  %}Customer send mail here for best support{% endblock %}
{% block body %}

<div class="addtocart-center">
    <pre class="text-center">
            <h2>Write us a mail, we get you shortly !!</h2><h2><a class="primary" href="mailto:harshit.saxena2016@gmail.coom">Send Here</a></h2><h4> <a class="text-success" href="{% url 'EShop:mycart' %}"></a></h4>
        </pre>

</div>



{% endblock %}

templates/customerlogin.html
{% extends 'base.html' %}

{% block title %}Customer login{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3 class="text-center mt-2">Customer Login Form</h3>
            <hr>
            {% if error %}
            <li style="color: red;">{{error}}</li>
            {% endif %}
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-lg text-center">Login As a Customer</button>
            </form>

            <p class="mt-2"> <span>Forget Password? <a href="{% url 'EShop:resetpassword' %}"> Reset Here</a></span>
                <span class="ml-4">or don't have account? <a
                        href="{% url 'EShop:customerregistration' %}{% if request.GET.next%}?next={{request.GET.next}}{% endif %}">
                        Register
                        here</a></span>
            </p>
        </div>
    </div>
</div>
{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}

{% block title %} My profile {% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h3>DETAILS VIEWS</h3><hr>
                <p><span class="font-weight-bold">Name: </span>{{ customer.full_name }}</p>
                <p><span class="font-weight-bold">Username: </span>{{ customer.user.username }}</p>
                <p><span class="font-weight-bold">Email_ID: </span>{{ customer.user.email}}</p>
                <p><span class="font-weight-bold">Address: </span>{{ customer.address }}</p>
                <p><span class="font-weight-bold">Joined_on: </span>{{ customer.joined_on }}</p>

            </div>

            <div class="col-md-8">
                <h3>PREVIOUS ORDERS</h3><hr>
                <table class="table">
                    <thead>
                        <tr>
                            <th>S. N.</th>
                            <th>Order_ID</th>
                            <th>Amount</th>
                            <th>Ordered_On</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ord in orders %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> <a href="{% url 'EShop:customerorderdetail' ord.id %}"> #Order_{{ord.id}}</a></td>
                                <td>{{ord.total}}</td>
                                <td>{{ord.created_at | timesince}} ago</td>
                                <td class="text-danger">{{ord.order_status}}</td>
                            </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}

{% block title %}Customer Registration{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3 class="text-center mt-2">Customer Registration Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-lg">Register As a Customer</button>

            </form>
            <p class="mt-3">already have a account? <a href="{% url 'EShop:customerlogin' %}">Login Here</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %}MyCart{% endblock %}

{% block body %}
<div class="container mt-3">
    <div class="row">
        <div class="mx-auto col-md-8">
            <ul class="billing p0">
                <li class="billing-detail">
                    <h4>Items in my cart</h4>
                </li>
                <li class="cart-update"><a style="color: tomato;" href="{% url 'EShop:emptycart' %}">Trash Cart</a></li>
            </ul>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>S.N.</th>
                        <th>Image</th>
                        <th>Products</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                            <td>{{forloop.counter}}</td>
                            <td>
                                <img class="img-fluid" src="{{cp.product.image.url}}" style="height: 100px; object-fit: contain;" alt="">
                            </td>
                            <td>{{cp.product.title}}</td>
                            <td>{{cp.rate}}</td>
                            <td>{{cp.quantity }}</td>
                            <td>{{cp.subtotal}}</td>
                            <td><div class="text-center">
                                <a href="{% url 'EShop:managecart' cp.id %}?action=dcr">
                                    <span class="btn btn-warning dcr">-</span>
                                </a><br>
                                
                                <a href="{% url 'EShop:managecart' cp.id %}?action=inc">
                                    <span class="inc btn btn-success">+</span>
                                </a><br>
                                <a href="{% url 'EShop:managecart' cp.id %}?action=rmv">
                                    <span class="rmv btn btn-danger">*</span>
                                </a>
                            </div>
                            </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            {% if cart.cartproduct_set.all %}
            <h4>Total RS. {{cart.total}} 
            <a class="ml-5" href="{% url 'EShop:checkout' %}"><button class="btn btn-lg">Go to Checkout</button></a>
            </h4>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/productdetail.html
{% extends 'base.html' %}

{% block title %} {{productdetail.title}}{% endblock %}

{% block body %}
    <div class="">
        <!-- <h3 class="my-3">{{productdetail.title}} </h3><hr> -->
        <div class="row">
            <div class="col-md-6 product-image">
                <img src="{{productdetail.image.url }}"  class="img-fluid" alt="">
                <div class="row">
                    {% for pi in productdetail.productimage_set.all %}
                    <div class="col-md-6 product-image">
                        <img class="image-fluid" height="450px" width="350px" src="{{ pi.image.url }}" alt="">
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                <h4 class="mt20 text-uppercase">{{ productdetail.category}} </h4>
                <h4 class="fw400">{{ productdetail.title}} (viewed {{productdetail.view_count}})</h4>
                <hr>
                <h5 class="price">RS. {{ productdetail.selling_price}} <strike> RS. {{ productdetail.marked_price}}</strike> </h5>
                <div class="green-text">
                    inclusive of all taxes
                </div>
                <button class="btn btn-lg">
                <a href="{% url 'EShop:addtocart' productdetail.id  %}">ADD TO CART</a>
                </button>
                <hr>

                <h4 class="fw400">WARRANTY: {{productdetail.warranty}} </h4>
                <h4 class="fw400">RETURN POLICY: {{productdetail.return_policy}} </h4>
                <br>
                <h4 class="mb20">Product Details</h4>
                <h4 class="fw300 lh mr-4">
                    {{productdetail.description}}
                </h4>
            </div>
        </div>
        
    </div>


{% endblock %}

templates/resetpassword.html
{% extends 'base.html' %}

{% block title %} Reset Password | EShop {% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">
                <h3 class="text-center mt-2">Reset Password Form</h3><hr>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button class="btn btn-danger">Get Reset Link</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} Search result {% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span style="color:royalblue">"{{request.GET.keyword}}"</span> </h3>
            <hr>
        </div>

    </div>
    {% for result in results %}
    <div class="row">
        <div class="col-md-4">
            <img  src="{{ result.image.url }}" class="img-fluid"  alt="">
        </div>
        <div class="col-md-8">
            <a href="{% url 'EShop:productdetail' result.slug %}"> {{result.title}}</a>
            <hr><br>
            <span  class="ml-3 font-weight-bold">Rs {{result.selling_price|intcomma}}</span> <br>
            {{result.description|truncatewords:40}} <br>
            <p class="mt-2">Return Policy: {{result.return_policy}} </p>
            <a href="{% url 'EShop:addtocart' result.id  %}" class="btn btn-primary">Add To Cart</a>
        </div>
    </div>
    <hr>
    {% endfor %}

</div>

{% endblock %}